---
# handlers file for 389-ds
- name: restart dirsrv
  #  service: name=dirsrv.target state=restarted
  systemd: name=dirsrv.target state=restarted

- name: restart dirsrv-admin
  #  service: name=dirsrv-admin state=restarted
  systemd: name=dirsrv-admin state=restarted

